[dev]
  command = "bun install && bun run dev"
  publish = "dist"

[build]
  command = "bun install && bun run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Robots-Tag = "index"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "robots.txt"
  status = 200
